-- ============================================
-- DIYA PHARMA — Diaper Products Database Schema
-- Run this in Supabase SQL Editor
-- ============================================

-- 1. Diaper Categories
CREATE TABLE public.diaper_categories (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT DEFAULT '',
  icon TEXT DEFAULT '',
  display_order INTEGER DEFAULT 0
);

ALTER TABLE public.diaper_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read diaper_categories" ON public.diaper_categories FOR SELECT USING (true);
CREATE POLICY "Full access diaper_categories" ON public.diaper_categories FOR ALL USING (true);

INSERT INTO public.diaper_categories (name, slug, description, icon, display_order) VALUES
('Pant Style Diapers', 'pant-style', 'Easy pull-up style for active adults. Feels like regular underwear.', '🩲', 1),
('Tape Style Diapers', 'tape-style', 'Adjustable adhesive tape diapers for bedridden patients.', '🏥', 2),
('Underpads', 'underpads', 'Disposable bed protection sheets for hygiene and comfort.', '🛏️', 3);


-- 2. Diaper Products
CREATE TABLE public.diaper_products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  category_id BIGINT REFERENCES public.diaper_categories(id),
  description TEXT DEFAULT '',
  features TEXT[] DEFAULT '{}',
  sizes JSONB DEFAULT '[]',
  image_main TEXT DEFAULT '',
  image_side TEXT DEFAULT '',
  image_back TEXT DEFAULT '',
  image_top TEXT DEFAULT '',
  image_pack TEXT DEFAULT '',
  rating DECIMAL(2,1) DEFAULT 4.5,
  in_stock BOOLEAN DEFAULT true,
  is_new BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- sizes column stores JSON array like:
-- [{"size":"M","mrp":599,"sale_price":499,"pack_qty":10},{"size":"L","mrp":649,"sale_price":549,"pack_qty":10}]

ALTER TABLE public.diaper_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read diaper_products" ON public.diaper_products FOR SELECT USING (true);
CREATE POLICY "Full access diaper_products" ON public.diaper_products FOR ALL USING (true);


-- 3. Seed Data — All 5 Brands with placeholder prices

-- ===== DIGNITY (ROMSONS) =====
INSERT INTO public.diaper_products (name, brand, category_id, description, features, sizes, rating, in_stock, is_new) VALUES
(
  'Dignity Magna Adult Diaper',
  'Dignity (Romsons)',
  1,
  'High-absorption pant-style diaper with 8-10 hours protection. Super absorbent core with wetness indicator.',
  '{"8-10 Hours Protection","Super Absorbent Core","Wetness Indicator","Odour Lock Technology","Soft Waistband"}',
  '[{"size":"M","waist":"24-36 inch","mrp":450,"sale_price":380,"pack_qty":10},{"size":"L","waist":"36-48 inch","mrp":499,"sale_price":420,"pack_qty":10},{"size":"XL","waist":"48-57 inch","mrp":549,"sale_price":460,"pack_qty":10},{"size":"XXL","waist":"57-66 inch","mrp":599,"sale_price":499,"pack_qty":10}]',
  4.3, true, false
),
(
  'Dignity Premium Adult Diaper',
  'Dignity (Romsons)',
  1,
  'Premium pant-style diaper with 10-12 hours absorption. Breathable material with aloe vera extract.',
  '{"10-12 Hours Protection","Breathable Fabric","Aloe Vera Layer","Anti-Leak Guards","Skin Friendly"}',
  '[{"size":"M","waist":"24-36 inch","mrp":599,"sale_price":499,"pack_qty":10},{"size":"L","waist":"36-48 inch","mrp":649,"sale_price":549,"pack_qty":10},{"size":"XL","waist":"48-57 inch","mrp":699,"sale_price":599,"pack_qty":10},{"size":"XXL","waist":"57-66 inch","mrp":749,"sale_price":649,"pack_qty":10}]',
  4.5, true, true
),
(
  'Dignity Overnight Adult Diaper',
  'Dignity (Romsons)',
  2,
  'Tape-style overnight diaper with 12-16 hours protection. Ideal for bedridden patients.',
  '{"12-16 Hours Protection","Tape-Style Fastening","Maximum Absorbency","Standing Leak Guards","Breathable Back Sheet"}',
  '[{"size":"M","waist":"24-36 inch","mrp":699,"sale_price":590,"pack_qty":10},{"size":"L","waist":"36-48 inch","mrp":749,"sale_price":630,"pack_qty":10},{"size":"XL","waist":"48-57 inch","mrp":799,"sale_price":670,"pack_qty":10},{"size":"XXL","waist":"57-66 inch","mrp":849,"sale_price":720,"pack_qty":10}]',
  4.6, true, true
);

-- ===== FRIENDS =====
INSERT INTO public.diaper_products (name, brand, category_id, description, features, sizes, rating, in_stock, is_new) VALUES
(
  'Friends Easy Adult Diaper Pants',
  'Friends',
  1,
  'Pant-style diaper with high absorption capacity. Aloe vera enriched with leak-proof technology.',
  '{"High Absorption","Aloe Vera Enriched","Leak-Proof Technology","Unisex Design","Soft Elastic Waist"}',
  '[{"size":"M","waist":"24-34 inch","mrp":399,"sale_price":340,"pack_qty":10},{"size":"L","waist":"34-45 inch","mrp":449,"sale_price":380,"pack_qty":10},{"size":"XL","waist":"45-56 inch","mrp":499,"sale_price":420,"pack_qty":10},{"size":"XXL","waist":"56-66 inch","mrp":549,"sale_price":460,"pack_qty":10}]',
  4.4, true, false
),
(
  'Friends Premium Adult Diaper Pants',
  'Friends',
  1,
  'Premium pull-up style diaper with 12-hour absorption and 3D leak guard.',
  '{"12 Hours Protection","3D Leak Guard","Ultra Thin Design","Dermatologically Tested","Tear-Away Sides"}',
  '[{"size":"M","waist":"24-34 inch","mrp":549,"sale_price":460,"pack_qty":10},{"size":"L","waist":"34-45 inch","mrp":599,"sale_price":499,"pack_qty":10},{"size":"XL","waist":"45-56 inch","mrp":649,"sale_price":549,"pack_qty":10},{"size":"XXL","waist":"56-66 inch","mrp":699,"sale_price":590,"pack_qty":10}]',
  4.5, true, true
),
(
  'Friends Classic Adult Tape Diaper',
  'Friends',
  2,
  'Tape-style diaper with adjustable tabs for caregivers. Maximum protection for bedridden patients.',
  '{"Adjustable Tape Tabs","Super Absorbent Polymer","Anti-Bacterial Layer","Wetness Indicator","Refastenable Design"}',
  '[{"size":"M","waist":"24-34 inch","mrp":499,"sale_price":420,"pack_qty":10},{"size":"L","waist":"34-45 inch","mrp":549,"sale_price":460,"pack_qty":10},{"size":"XL","waist":"45-56 inch","mrp":599,"sale_price":499,"pack_qty":10}]',
  4.3, true, false
);

-- ===== LIFREE =====
INSERT INTO public.diaper_products (name, brand, category_id, description, features, sizes, rating, in_stock, is_new) VALUES
(
  'Lifree Extra Absorbent Pants',
  'Lifree',
  1,
  'Extra-absorbent adult diaper pants with soft waistband for maximum comfort.',
  '{"Extra Absorbent Core","Soft Waistband","Quick Dry Surface","360° Fit","Odour Control"}',
  '[{"size":"M","waist":"24-33 inch","mrp":499,"sale_price":420,"pack_qty":10},{"size":"L","waist":"33-44 inch","mrp":549,"sale_price":460,"pack_qty":10},{"size":"XL","waist":"44-55 inch","mrp":599,"sale_price":499,"pack_qty":10},{"size":"XXL","waist":"55-65 inch","mrp":649,"sale_price":549,"pack_qty":10}]',
  4.6, true, true
),
(
  'Lifree Comfort Tape Diaper',
  'Lifree',
  2,
  'Tape-style diaper with superior absorbency designed for overnight use and bedridden care.',
  '{"Superior Absorbency","Comfortable Tape Closure","Breathable Material","Overnight Protection","Hypoallergenic"}',
  '[{"size":"M","waist":"24-33 inch","mrp":549,"sale_price":460,"pack_qty":10},{"size":"L","waist":"33-44 inch","mrp":599,"sale_price":499,"pack_qty":10},{"size":"XL","waist":"44-55 inch","mrp":649,"sale_price":549,"pack_qty":10}]',
  4.4, true, false
);

-- ===== KAREIN =====
INSERT INTO public.diaper_products (name, brand, category_id, description, features, sizes, rating, in_stock, is_new) VALUES
(
  'KareIn Adult Diaper Pants',
  'KareIn',
  1,
  'Comfortable antibacterial pant-style diaper with advanced odour control technology.',
  '{"Antibacterial Layer","Odour Control","Cloth-Like Feel","Leak-Proof Barriers","Easy Tear Sides"}',
  '[{"size":"M","waist":"24-34 inch","mrp":399,"sale_price":330,"pack_qty":10},{"size":"L","waist":"34-45 inch","mrp":449,"sale_price":370,"pack_qty":10},{"size":"XL","waist":"45-56 inch","mrp":499,"sale_price":420,"pack_qty":10},{"size":"XXL","waist":"56-66 inch","mrp":549,"sale_price":460,"pack_qty":10}]',
  4.2, true, false
),
(
  'KareIn Premium Underpads',
  'KareIn',
  3,
  'Disposable bed protection underpads. Highly absorbent with waterproof backing.',
  '{"Super Absorbent","Waterproof Backing","Non-Woven Surface","60x90cm Size","5-Layer Protection"}',
  '[{"size":"60x90cm","waist":"","mrp":349,"sale_price":290,"pack_qty":10},{"size":"60x90cm","waist":"","mrp":599,"sale_price":499,"pack_qty":20}]',
  4.3, true, false
);

-- ===== SENI =====
INSERT INTO public.diaper_products (name, brand, category_id, description, features, sizes, rating, in_stock, is_new) VALUES
(
  'Seni Active Adult Diaper Pants',
  'Seni',
  1,
  'Breathable and dermatologically tested adult diaper pants for sensitive skin.',
  '{"Dermatologically Tested","Breathable Material","For Sensitive Skin","Double Absorbent Core","Elastic Waistband"}',
  '[{"size":"M","waist":"24-34 inch","mrp":549,"sale_price":460,"pack_qty":10},{"size":"L","waist":"34-45 inch","mrp":599,"sale_price":499,"pack_qty":10},{"size":"XL","waist":"45-56 inch","mrp":649,"sale_price":549,"pack_qty":10},{"size":"XXL","waist":"56-66 inch","mrp":699,"sale_price":590,"pack_qty":10}]',
  4.7, true, true
),
(
  'Seni Super Classic Tape Diaper',
  'Seni',
  2,
  'Premium tape-style diaper for bedridden patients with breathable outer layer.',
  '{"Breathable Outer Layer","Triple Protection System","Anatomical Shape","Re-Closable Tapes","Odour Stop System"}',
  '[{"size":"M","waist":"24-34 inch","mrp":599,"sale_price":499,"pack_qty":10},{"size":"L","waist":"34-45 inch","mrp":649,"sale_price":549,"pack_qty":10},{"size":"XL","waist":"45-56 inch","mrp":699,"sale_price":590,"pack_qty":10}]',
  4.5, true, false
),
(
  'Seni Soft Underpads',
  'Seni',
  3,
  'Hypoallergenic disposable underpads designed for sensitive skin with maximum absorption.',
  '{"Hypoallergenic","Super Absorbent Core","Non-Slip Bottom","Soft Top Layer","Dermatologically Tested"}',
  '[{"size":"60x60cm","waist":"","mrp":299,"sale_price":249,"pack_qty":10},{"size":"60x90cm","waist":"","mrp":399,"sale_price":330,"pack_qty":10}]',
  4.4, true, false
);
